/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthVehiclesRouteImport } from './routes/_auth.vehicles'
import { Route as AuthVehicleTypesRouteImport } from './routes/_auth.vehicle-types'
import { Route as AuthOrdersRouteImport } from './routes/_auth.orders'
import { Route as AuthLocationsRouteImport } from './routes/_auth.locations'
import { Route as AuthComputesRouteImport } from './routes/_auth.computes'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVehiclesRoute = AuthVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVehicleTypesRoute = AuthVehicleTypesRouteImport.update({
  id: '/vehicle-types',
  path: '/vehicle-types',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOrdersRoute = AuthOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLocationsRoute = AuthLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AuthRoute,
} as any)
const AuthComputesRoute = AuthComputesRouteImport.update({
  id: '/computes',
  path: '/computes',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/computes': typeof AuthComputesRoute
  '/locations': typeof AuthLocationsRoute
  '/orders': typeof AuthOrdersRoute
  '/vehicle-types': typeof AuthVehicleTypesRoute
  '/vehicles': typeof AuthVehiclesRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/computes': typeof AuthComputesRoute
  '/locations': typeof AuthLocationsRoute
  '/orders': typeof AuthOrdersRoute
  '/vehicle-types': typeof AuthVehicleTypesRoute
  '/vehicles': typeof AuthVehiclesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/computes': typeof AuthComputesRoute
  '/_auth/locations': typeof AuthLocationsRoute
  '/_auth/orders': typeof AuthOrdersRoute
  '/_auth/vehicle-types': typeof AuthVehicleTypesRoute
  '/_auth/vehicles': typeof AuthVehiclesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/computes'
    | '/locations'
    | '/orders'
    | '/vehicle-types'
    | '/vehicles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/computes'
    | '/locations'
    | '/orders'
    | '/vehicle-types'
    | '/vehicles'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/computes'
    | '/_auth/locations'
    | '/_auth/orders'
    | '/_auth/vehicle-types'
    | '/_auth/vehicles'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/vehicles': {
      id: '/_auth/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof AuthVehiclesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/vehicle-types': {
      id: '/_auth/vehicle-types'
      path: '/vehicle-types'
      fullPath: '/vehicle-types'
      preLoaderRoute: typeof AuthVehicleTypesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/orders': {
      id: '/_auth/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthOrdersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/locations': {
      id: '/_auth/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof AuthLocationsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/computes': {
      id: '/_auth/computes'
      path: '/computes'
      fullPath: '/computes'
      preLoaderRoute: typeof AuthComputesRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthComputesRoute: typeof AuthComputesRoute
  AuthLocationsRoute: typeof AuthLocationsRoute
  AuthOrdersRoute: typeof AuthOrdersRoute
  AuthVehicleTypesRoute: typeof AuthVehicleTypesRoute
  AuthVehiclesRoute: typeof AuthVehiclesRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthComputesRoute: AuthComputesRoute,
  AuthLocationsRoute: AuthLocationsRoute,
  AuthOrdersRoute: AuthOrdersRoute,
  AuthVehicleTypesRoute: AuthVehicleTypesRoute,
  AuthVehiclesRoute: AuthVehiclesRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
